export const GetAllCategoryUrl = "/api/v1/category"
export const GetAllSubCategoryUrl = "/api/v1/subCategory"
export const GetAllVariationUrl = "/api/v1/variation-template"
export const deleteFileFromServerUrl = "/api/v1/media/delete"
export const createProductUrl = "/api/v1/product"
export const getAllProductUrl = "/api/v1/product"